### ISSUE TITLE
Which transcript will it annotated if there is multi-transcript at the same chromosome site

### ISSUE THREAD

**Issue by Lozzard** [Codezy99/cliProfiler#2]
Hello,
Thanks for this convenient and useful package.  I noticed that the plot it made by metaGeneProfile() can be very different from another R package "Guitar". So I'm wonder that which transcript will it annotated if there is multi-transcript at the same chromosome site. Thank you

**Comment by Codezy99** [comment]
Hello @Lozzard,

the peaks/sites which overlap to more than one transcripts will be assigned to the transcripts follow the hierarchy:
1) smallest level
2) smallest transcript support level
3) longest transcript

The information about `level` and `transcript_support_level` can be found in the link https://www.gencodegenes.org/pages/data_format.html. The basic idea that we use for assigning the peaks to transcripts is assign them to the more reliable annotated transcripts. I hope this answers your question.

Regarding the difference between CLIProfiler and Guitar, I guess it could be a smooth problem of the density plot. Since in Guitar they shrink the length of 5'UTR in the plot, even you have only very few peaks in the 5'UTR, the curve will still look pretty high at 5'UTR. For checking that, you can count the number of peaks at 5'UTR to find out more detail about your data.

Best regards,
You Zhou

**Comment by Lozzard** [comment]
Thank you for your response
